import { BodyRecord, MetricDefinition, MetricKey } from '../types';

export const INITIAL_RECORDS: BodyRecord[] = [
  {
    id: 'rec-1',
    date: '2026/08/31 13:36',
    timestamp: new Date('2026-08-31T13:36:00+08:00').getTime(),
    timezone: 'Asia/Taipei',
    weight: 87.5,
    bodyFatPct: 28.0,
    bodyFatKg: 24.5,
    visceralFat: 14.0,
    basalMetabolism: 1858,
    skeletalMusclePct: 30.5,
    skeletalMuscleKg: 26.7,
    skeletalMuscleArmsPct: 36.2,
    skeletalMuscleTrunkPct: 22.6,
    skeletalMuscleLegsPct: 47.8,
    subcutaneousFatPct: 19.8,
    subcutaneousFatArmsPct: 26.5,
    subcutaneousFatTrunkPct: 18.2,
    subcutaneousFatLegsPct: 26.7,
    bmi: 28.7,
    bodyAge: 52,
    modelName: 'HBF-702T',
  },
  {
    id: 'rec-2',
    date: '2026/09/01 21:54',
    timestamp: new Date('2026-09-01T21:54:00+08:00').getTime(),
    timezone: 'Asia/Taipei',
    weight: 86.9,
    bodyFatPct: 28.4,
    bodyFatKg: 24.7,
    visceralFat: 13.5,
    basalMetabolism: 1846,
    skeletalMusclePct: 30.3,
    skeletalMuscleKg: 26.3,
    skeletalMuscleArmsPct: 36.1,
    skeletalMuscleTrunkPct: 22.4,
    skeletalMuscleLegsPct: 47.6,
    subcutaneousFatPct: 20.0,
    subcutaneousFatArmsPct: 27.1,
    subcutaneousFatTrunkPct: 18.4,
    subcutaneousFatLegsPct: 27.3,
    bmi: 28.5,
    bodyAge: 52,
    modelName: 'HBF-702T',
  },
  {
    id: 'rec-3',
    date: '2026/09/03 07:37',
    timestamp: new Date('2026-09-03T07:37:00+08:00').getTime(),
    timezone: 'Asia/Taipei',
    weight: 86.2,
    bodyFatPct: 29.5,
    bodyFatKg: 25.4,
    visceralFat: 13.5,
    basalMetabolism: 1827,
    skeletalMusclePct: 29.8,
    skeletalMuscleKg: 25.7,
    skeletalMuscleArmsPct: 35.6,
    skeletalMuscleTrunkPct: 21.7,
    skeletalMuscleLegsPct: 47.2,
    subcutaneousFatPct: 20.7,
    subcutaneousFatArmsPct: 28.6,
    subcutaneousFatTrunkPct: 18.9,
    subcutaneousFatLegsPct: 28.9,
    bmi: 28.3,
    bodyAge: 52,
    modelName: 'HBF-702T',
  },
];

export const METRIC_DEFINITIONS: Record<MetricKey, MetricDefinition> = {
  weight: {
    key: 'weight',
    label: '體重',
    shortLabel: '體重',
    unit: 'kg',
    category: 'main',
    color: '#3b82f6', // blue
    fillColor: 'rgba(59, 130, 246, 0.12)',
    decimals: 2,
    description: '整體人體總重量，包含水分、脂肪、肌肉與骨骼。',
    normalRange: { min: 60, max: 75, label: '依個人身高換算標準' },
    goodDirection: 'neutral',
  },
  bodyFatPct: {
    key: 'bodyFatPct',
    label: '體脂肪率',
    shortLabel: '體脂率',
    unit: '%',
    category: 'fat',
    color: '#f97316', // orange
    fillColor: 'rgba(249, 115, 22, 0.12)',
    decimals: 1,
    description: '體內脂肪重量佔總體重之百分比，男一般標準為 10-20%，女為 20-30%。',
    normalRange: { min: 10.0, max: 20.0, label: '男性 10-20% / 女性 20-30%' },
    goodDirection: 'lower',
  },
  bodyFatKg: {
    key: 'bodyFatKg',
    label: '體脂肪重量',
    shortLabel: '脂肪量',
    unit: 'kg',
    category: 'fat',
    color: '#ea580c', // dark orange
    fillColor: 'rgba(234, 88, 12, 0.12)',
    decimals: 1,
    description: '全身脂肪之實體總重量，減脂計畫的核心觀察指標。',
    goodDirection: 'lower',
  },
  skeletalMusclePct: {
    key: 'skeletalMusclePct',
    label: '骨骼肌率',
    shortLabel: '骨骼肌%',
    unit: '%',
    category: 'muscle',
    color: '#10b981', // emerald
    fillColor: 'rgba(16, 185, 129, 0.12)',
    decimals: 1,
    description: '骨骼肌佔體重的比例，骨骼肌越高，基礎代謝越旺盛，維持好體態不易復胖。',
    normalRange: { min: 32.0, max: 37.0, label: '男性標準約 32-37%' },
    goodDirection: 'higher',
  },
  skeletalMuscleKg: {
    key: 'skeletalMuscleKg',
    label: '骨骼肌重量',
    shortLabel: '肌肉量',
    unit: 'kg',
    category: 'muscle',
    color: '#059669', // dark green
    fillColor: 'rgba(5, 150, 105, 0.12)',
    decimals: 1,
    description: '全身骨骼肌的實際重量，減重期間應盡力保留肌肉量，避免代謝下降。',
    goodDirection: 'higher',
  },
  visceralFat: {
    key: 'visceralFat',
    label: '內臟脂肪程度',
    shortLabel: '內臟脂肪',
    unit: '級',
    category: 'fat',
    color: '#ef4444', // red
    fillColor: 'rgba(239, 68, 68, 0.12)',
    decimals: 1,
    description: '圍繞在腹部內臟周圍的脂肪程度。1-9 標準，10-14 偏高，15 以上危險。',
    normalRange: { min: 1.0, max: 9.0, label: '標準 1-9' },
    goodDirection: 'lower',
  },
  bmi: {
    key: 'bmi',
    label: '身體質量指數 (BMI)',
    shortLabel: 'BMI',
    unit: '',
    category: 'main',
    color: '#8b5cf6', // purple
    fillColor: 'rgba(139, 92, 246, 0.12)',
    decimals: 1,
    description: '體重(kg) / 身高(m)平方。衛福部標準：18.5-24.0 為正常，24.0-27.0 過重，>27 肥胖。',
    normalRange: { min: 18.5, max: 24.0, label: '標準 18.5-24.0' },
    goodDirection: 'lower',
  },
  basalMetabolism: {
    key: 'basalMetabolism',
    label: '基礎代謝率',
    shortLabel: '基代',
    unit: 'kcal',
    category: 'metabolic',
    color: '#06b6d4', // cyan
    fillColor: 'rgba(6, 182, 212, 0.12)',
    decimals: 0,
    description: '維持人體一天最基本生理運作所需熱量，肌肉量越多則基代越高。',
    goodDirection: 'higher',
  },
  bodyAge: {
    key: 'bodyAge',
    label: '身體年齡',
    shortLabel: '體年齡',
    unit: '歲',
    category: 'metabolic',
    color: '#6366f1', // indigo
    fillColor: 'rgba(99, 102, 241, 0.12)',
    decimals: 0,
    description: '依據基礎代謝、體重、骨骼肌率與體脂率綜合推算之生理年齡。',
    goodDirection: 'lower',
  },
  subcutaneousFatPct: {
    key: 'subcutaneousFatPct',
    label: '皮下脂肪率 (全身)',
    shortLabel: '皮下脂肪',
    unit: '%',
    category: 'fat',
    color: '#f59e0b', // amber
    fillColor: 'rgba(245, 158, 11, 0.12)',
    decimals: 1,
    description: '全身皮膚下方脂肪比例，影響外觀線條與保暖。',
    goodDirection: 'lower',
  },
  skeletalMuscleArmsPct: {
    key: 'skeletalMuscleArmsPct',
    label: '雙臂骨骼肌率',
    shortLabel: '雙臂肌率',
    unit: '%',
    category: 'segmental',
    color: '#14b8a6', // teal
    fillColor: 'rgba(20, 184, 166, 0.12)',
    decimals: 1,
    description: '手臂部位的骨骼肌肉佔比，反映上肢肌力儲備。',
    goodDirection: 'higher',
  },
  skeletalMuscleTrunkPct: {
    key: 'skeletalMuscleTrunkPct',
    label: '身軀骨骼肌率',
    shortLabel: '身軀肌率',
    unit: '%',
    category: 'segmental',
    color: '#0d9488', // dark teal
    fillColor: 'rgba(13, 148, 136, 0.12)',
    decimals: 1,
    description: '軀幹核心肌肉比例，對姿態、腰背脊椎支撐至關重要。',
    goodDirection: 'higher',
  },
  skeletalMuscleLegsPct: {
    key: 'skeletalMuscleLegsPct',
    label: '雙腳骨骼肌率',
    shortLabel: '雙腳肌率',
    unit: '%',
    category: 'segmental',
    color: '#047857', // forest green
    fillColor: 'rgba(4, 120, 87, 0.12)',
    decimals: 1,
    description: '下肢腿部肌肉佔比，人體最大肌群所在，行走活力與代謝樞紐。',
    goodDirection: 'higher',
  },
  subcutaneousFatArmsPct: {
    key: 'subcutaneousFatArmsPct',
    label: '雙臂皮下脂肪率',
    shortLabel: '雙臂皮脂',
    unit: '%',
    category: 'segmental',
    color: '#fb923c', // light orange
    fillColor: 'rgba(251, 146, 60, 0.12)',
    decimals: 1,
    description: '雙臂皮下脂肪比例。',
    goodDirection: 'lower',
  },
  subcutaneousFatTrunkPct: {
    key: 'subcutaneousFatTrunkPct',
    label: '身軀皮下脂肪率',
    shortLabel: '身軀皮脂',
    unit: '%',
    category: 'segmental',
    color: '#f97316',
    fillColor: 'rgba(249, 115, 22, 0.12)',
    decimals: 1,
    description: '軀幹腹腰部皮下脂肪比例，常與肚腩、腰圍相關。',
    goodDirection: 'lower',
  },
  subcutaneousFatLegsPct: {
    key: 'subcutaneousFatLegsPct',
    label: '雙腳皮下脂肪率',
    shortLabel: '雙腳皮脂',
    unit: '%',
    category: 'segmental',
    color: '#d97706',
    fillColor: 'rgba(217, 119, 6, 0.12)',
    decimals: 1,
    description: '臀腿下肢皮下脂肪比例。',
    goodDirection: 'lower',
  },
};
